-- Schema dump from old Memora project
-- Generated 2026-04-24T08:06:10.318Z

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS "customer_orders" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "slug" text NOT NULL,
  "subject_type" text NOT NULL,
  "subject_name" text NOT NULL,
  "birth_date" date,
  "passing_date" date,
  "dedication" text,
  "album_style" text NOT NULL,
  "music_choice" jsonb,
  "uploaded_files" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "album_layout" jsonb,
  "contact_name" text NOT NULL,
  "contact_email" text NOT NULL,
  "contact_phone" text,
  "shipping_address" jsonb,
  "shipping_zone" text,
  "price_chf" numeric(10,2),
  "payment_status" text DEFAULT 'pending'::text NOT NULL,
  "stripe_session_id" text,
  "status" text DEFAULT 'new'::text NOT NULL,
  "is_test" boolean DEFAULT false NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "published_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "discount_codes" (
  "code" text NOT NULL,
  "discount_type" text NOT NULL,
  "value" numeric NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "valid_until" timestamptz,
  "max_uses" integer,
  "times_used" integer DEFAULT 0 NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "product_type" text,
  "options_summary" text,
  "total_price" numeric,
  "subject_details" text,
  "music_choice" text,
  "contact_name" text,
  "contact_email" text,
  "contact_phone" text,
  "billing_address" text,
  "notes" text,
  "preview_file_path" text,
  "canva_link" text,
  "slug" text,
  "album_style" text,
  "shipping_cost" numeric,
  "billing_country" text,
  "applied_discount_code" text,
  "uploaded_files" jsonb,
  "payment_status" text DEFAULT '"pending"'::text
);

CREATE TABLE IF NOT EXISTS "partner_orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "contact_name" text,
  "music_choice" text,
  "album_style" text,
  "notes" text,
  "partner_key" text DEFAULT 'flueckiger'::text,
  "slug" text,
  "canva_link" text,
  "uploaded_files" jsonb DEFAULT '[]'::jsonb,
  "album_layout" jsonb
);

CREATE TABLE IF NOT EXISTS "tag_slugs" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "slug" text NOT NULL,
  "batch_label" text,
  "assigned_order_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "assigned_at" timestamptz
);

ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_album_style_check" CHECK ((album_style = ANY (ARRAY['modern'::text, 'classic'::text, 'vintage'::text])));
ALTER TABLE discount_codes ADD CONSTRAINT "discount_codes_value_check" CHECK ((value > (0)::numeric));
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_payment_status_check" CHECK ((payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'test'::text, 'refunded'::text])));
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_shipping_zone_check" CHECK ((shipping_zone = ANY (ARRAY['CH'::text, 'EU'::text, 'WORLD'::text])));
ALTER TABLE discount_codes ADD CONSTRAINT "discount_codes_discount_type_check" CHECK ((discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])));
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_status_check" CHECK ((status = ANY (ARRAY['new'::text, 'in-progress'::text, 'published'::text, 'cancelled'::text])));
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_subject_type_check" CHECK ((subject_type = ANY (ARRAY['human'::text, 'pet'::text])));
ALTER TABLE tag_slugs ADD CONSTRAINT "tag_slugs_assigned_order_id_fkey" FOREIGN KEY (assigned_order_id) REFERENCES customer_orders(id) ON DELETE SET NULL;
ALTER TABLE discount_codes ADD CONSTRAINT "discount_codes_pkey" PRIMARY KEY (code);
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_pkey" PRIMARY KEY (id);
ALTER TABLE orders ADD CONSTRAINT "orders_pkey" PRIMARY KEY (id);
ALTER TABLE partner_orders ADD CONSTRAINT "partner_orders_pkey" PRIMARY KEY (id);
ALTER TABLE tag_slugs ADD CONSTRAINT "tag_slugs_pkey" PRIMARY KEY (id);
ALTER TABLE partner_orders ADD CONSTRAINT "partner_orders_slug_key" UNIQUE (slug);
ALTER TABLE customer_orders ADD CONSTRAINT "customer_orders_slug_key" UNIQUE (slug);
ALTER TABLE orders ADD CONSTRAINT "orders_slug_unique" UNIQUE (slug);
ALTER TABLE tag_slugs ADD CONSTRAINT "tag_slugs_slug_key" UNIQUE (slug);

CREATE INDEX customer_orders_status_idx ON public.customer_orders USING btree (status);
CREATE INDEX customer_orders_is_test_idx ON public.customer_orders USING btree (is_test);
CREATE INDEX customer_orders_email_idx ON public.customer_orders USING btree (contact_email);
CREATE INDEX customer_orders_created_at_idx ON public.customer_orders USING btree (created_at DESC);
CREATE INDEX idx_orders_slug ON public.orders USING btree (slug);
CREATE INDEX tag_slugs_assigned_order_idx ON public.tag_slugs USING btree (assigned_order_id);
CREATE INDEX tag_slugs_batch_idx ON public.tag_slugs USING btree (batch_label);

CREATE OR REPLACE FUNCTION public.append_customer_order_files(order_id uuid, new_files jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  updated_files jsonb;
BEGIN
  IF jsonb_typeof(new_files) <> 'array' THEN
    RAISE EXCEPTION 'new_files must be a JSON array';
  END IF;

  UPDATE customer_orders
  SET uploaded_files = COALESCE(uploaded_files, '[]'::jsonb) || new_files
  WHERE id = order_id
  RETURNING uploaded_files INTO updated_files;

  IF updated_files IS NULL THEN
    RAISE EXCEPTION 'Order % not found', order_id;
  END IF;

  RETURN updated_files;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.customer_orders_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_discount_usage(code_to_increment text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Erhöhe Zähler nur, wenn Code existiert
  UPDATE public.discount_codes
  SET times_used = times_used + 1
  WHERE code = code_to_increment;
END;
$function$
;

CREATE TRIGGER customer_orders_updated_at BEFORE UPDATE ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION customer_orders_set_updated_at();
